Greeting.create(content: 'Hello & Welcome!')
Greeting.create(content: 'Good to see you! Welcome -from Rails-React app!')
Greeting.create(content: 'Good afternoon!')
Greeting.create(content: 'Welcome, its nice to have you here!')
Greeting.create(content: 'Hello there!')